# Generated by Django 2.0.3 on 2018-03-24 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Bug'), (2, 'Enhancement'), (3, 'Documentation')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (10, 'More information requested'), (20, 'Work in progress'), (30, 'Duplicate'), (40, 'Delivered'), (50, 'Failed verification'), (60, 'Closed, verified'), (61, 'Closed, not verified')], default=1)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_set', to=settings.AUTH_USER_MODEL)),
                ('filer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filer_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
